version: "3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - /home/mikael/dev/mysql2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - debian-dev-network
  ss4:
    container_name: ss4prod
    image: ss4prod
    ports:
      - "80:80"
    volumes:
       - /home/mikael/dev/cd/docker-ansible/docker/prod/apache2/sites-enabled:/etc/apache2/sites-enabled
    networks:
      - debian-dev-network 
networks:
  debian-dev-network:
    driver: bridge

